version: '3.7'

services:
    elastic04:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
        container_name: elastic04
        environment:
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
            - http.cors.enabled=true
            - http.cors.allow-origin=*
            - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
            - http.cors.allow-credentials=true
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - elastic04:/usr/share/elasticsearch/data
        ports:
            - '9200:9200'
        networks:
            - elastic

volumes:
    elastic04:

networks:
    elastic:
        driver: bridge
